{
    "Bild": "Image",
    "Beacons" :"Beacons",
    "Bereich" : "Area",
    "Kampagne" : "Campaign",
    "Bereich" : "Area",
    "Bereich hinzufugen"  : "Add Area",
    "Raum hinzufugen" : "Add room",
    "Kundenverwaltung" : "Customer Management",
    "Verwaltung" : "Administration",
    "Benutzer" : "User",
    "Rollen" : "Role",
    "Mein Profil ansehenandern" : "Change/View Profile",
    "Passwort andern" : "Change password",
    "Aktions / Handlungen" : "Actions",
    "Profil" : "Profile",
     "Name" : "Name",
    "Major" : "Major",
    "Minor" : "Minor",
    "Raum" : "Room",
    "Aktion zuweisen" : "Assign action",
    "Lochen" : "Delete",
    "Beacon hinzufugen" : "Add Beacon",
    "Beacon Hersteller" : "Beacon Manufacturers",
    "Wert" : "value",
    "Major Wert" : "Major value",
    "Minor Wert" : "Minor value",
    "Befindet sich in einem Raum" : "Located in one room",
    "Standort" : "location",
    "Breitengard" : "Breitengard",
    "Langenrad" : "degree of latitude",
    "Speichern" : "Save",
    "Aktualisierung" : "Update",
    "Abbrechen" : "abort",
    "+ Hinzufugen" : "+ Add",
    "Abmelden" : "Logout",
    "Kampagne hinzufugen" : "Add Campaign",
    "Aktiv" : "Active",
    "Zeitplan" : "schedule",
    "Durchzufuhrende Aktion" : "Action to",
    "Ausloser" : "Trigger",
    "Zeitpunkt" : "Time",
    "Haufigkeit" : "Frequency",
    "start" : "Start",
    "finish" : "Finish",
    "navigation" : "Navigation",
    "direction" : "Direction",
    "description" : "Description",
    "Beacon" : "Beacon",
    "forward" : "forward",
    "right" : "right",
    "left" : "left",
    "route active" : "Route active",
    "Employees" : "Employees",
    "Project" : "Project"
    	
    	
}